[build]
  command = "CI=false NODE_OPTIONS=--max-old-space-size=4096 npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  VITE_BUILD = "true"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = true